[env:giga_r1_wifi]
platform = arduino
board = giga_r1_wifi
framework = arduino
build_flags = 
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic
    -Wno-unused-parameter
lib_deps = 
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit GFX Library @ ^1.11.11
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    paulstoffregen/Time @ ^1.6.1
    mikalhart/TinyGPSPlus @ ^1.0.3
monitor_speed = 115200
